services:
  app:
    image: drupal
    ports:
      - 8080:80
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
